apiVersion: v1
kind: Service
metadata:
  name: tasky-svc-http
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: tasky
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
