apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: tasky
        image: eyembrad/tasky:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tasky-secret
              key: tasky-password
        - name: MONGODB_URI
          value: mongodb://mongouser:mongopassword@192.168.1.53:27017/?directConnection=true&serverSelectionTimeoutMS=2000&authSource=admin

