name: CI/CD to Kubernetes

on:
  pull_request:    # build image for PRs
  push:
    branches:
      - main       # build + deploy on merge to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug workflow context
        run: |
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Workflow file: $GITHUB_WORKFLOW_REF"
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=eyembrad/tasky
          IMAGE_TAG=latest
          echo "Building $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build   # make sure build runs first
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Build kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/tasky-app.yaml
          kubectl rollout restart deployment tasky
          kubectl rollout status deployment/tasky
