name: Snyk Security Scan

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  snyk-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'  # match your go.mod

      - name: Snyk Go Test
        uses: snyk/actions/golang@master
        with:
          command: test
          args: --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - name: Debug repo structure
        run: |
          pwd
          ls -lah
          ls -R assets

      - name: Snyk Code Test
        uses: snyk/actions/node@master
        with:
          command: code
          args: test tasky/assets/js/ --debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
